- id: doi:10.1038/s41586-024-07499-6
  title: Profiling phagosome proteins identifies PD-L1 as a fungal-binding receptor
  authors:
  - Kai Li
  - Avradip Chatterjee
  - Chen Qian
  - Katherine Lagree
  - Yang Wang
  - Courtney A. Becker
  - Michael R. Freeman
  - Ramachandran Murali
  - Wei Yang
  - David M. Underhill
  publisher: Nature
  date: '2024-06-05'
  link: https://doi.org/g9qvvz
  orcid: 0000-0003-3329-8125
  plugin: orcid.py
  file: orcid.yaml
  featured: true



